# Module: oversampling_rollup_integrity (cross-repo)
# Standing regression guard for the 2026-09-21 rollup bug (Jack): once
# per-cluster/per-stratum Achieved went uncapped (2026-09-20), every
# multi-stratum rollup (LGA / partner / national) that summed raw achieved
# and raw target and then subtracted or divided ONCE let an oversampled
# stratum's surplus cancel a different stratum's shortfall - a real
# interview in stratum A can never substitute for a household still needed
# in stratum B. The fix everywhere is cap/floor PER STRATUM first, then sum:
#   credited = sum(min(achieved_i, target_i))
#   remaining = sum(max(target_i - achieved_i, 0))
# with the identity credited + remaining == target holding by construction.
#
# This module checks the 1_sampling partner workbooks (the source last
# night's partner emails read verbatim). The dashboard-side twin lives in
# dashboard_deletion_identity.R (which already sources global.R once -
# not duplicated here to avoid a second ~1 min dashboard load).
library(dplyr)
library(readxl)

run_oversampling_rollup_integrity_checks <- function(log) {
  partner_dirs <- setdiff(list.dirs(PKG_ROOT, recursive = FALSE, full.names = FALSE), "_communications")

  n_checked <- 0
  pre_fix <- character(0)       # workbook still on the pre-2026-09-21 headline (no "Credited" row)
  bad_identity <- character(0)  # credited + still needed != total target
  bad_still <- character(0)     # README still needed != sum of Strata Summary per-row Still Needed
  bad_credited <- character(0)  # README credited != sum of per-row min(Achieved, Target)
  masked_now_visible <- character(0)  # raw achieved >= target but still needed > 0: the exact case the old headline hid

  for (p in partner_dirs) {
    wb <- list.files(file.path(PKG_ROOT, p), pattern = "sampling_points_summary\\.xlsx$", full.names = TRUE)
    if (length(wb) == 0) next
    wb <- wb[1]
    readme <- tryCatch(read_excel(wb, sheet = "README", col_names = FALSE, .name_repair = "minimal"), error = function(e) NULL)
    strata <- tryCatch(read_excel(wb, sheet = "Strata Summary"), error = function(e) NULL)
    if (is.null(readme) || is.null(strata)) { pre_fix <- c(pre_fix, p); next }

    lab <- as.character(readme[[1]])
    val <- as.character(readme[[2]])
    get_num <- function(prefix) {
      i <- which(startsWith(coalesce(lab, ""), prefix))[1]
      if (is.na(i)) NA_real_ else suppressWarnings(as.numeric(val[i]))
    }
    total_target <- get_num("Total target")
    achieved_raw <- get_num("Achieved so far")
    credited <- get_num("Credited toward target")
    still <- get_num("Still needed")
    if (any(is.na(c(total_target, credited, still)))) { pre_fix <- c(pre_fix, p); next }
    n_checked <- n_checked + 1

    if (abs((credited + still) - total_target) > 0.5) {
      bad_identity <- c(bad_identity, sprintf("%s (%s + %s != %s)", p, credited, still, total_target))
    }
    row_still <- sum(as.numeric(strata[["Still Needed"]]), na.rm = TRUE)
    row_cred <- sum(pmin(as.numeric(strata[["Achieved"]]), as.numeric(strata[["Target (design)"]])), na.rm = TRUE)
    if (abs(row_still - still) > 0.5) bad_still <- c(bad_still, sprintf("%s (README %s vs rows %s)", p, still, row_still))
    if (abs(row_cred - credited) > 0.5) bad_credited <- c(bad_credited, sprintf("%s (README %s vs rows %s)", p, credited, row_cred))
    if (!is.na(achieved_raw) && achieved_raw >= total_target && still > 0) {
      masked_now_visible <- c(masked_now_visible, sprintf("%s (raw %s >= target %s, yet %s still needed)", p, achieved_raw, total_target, still))
    }
  }

  log <- check_result(log, "oversampling_rollup_integrity", "Every partner workbook README is on the post-2026-09-21 headline (Credited / Still needed rows present)",
                       if (length(pre_fix) == 0) "PASS" else "FAIL",
                       sprintf("%d workbook(s) checked; %d still carry the old headline (no 'Credited toward target' row) or lack a Strata Summary sheet: %s - a workbook regenerated by a script that lost the fix, or never re-run since",
                               n_checked, length(pre_fix), paste(pre_fix, collapse = ", ")),
                       length(pre_fix))
  log <- check_result(log, "oversampling_rollup_integrity", "README headline: Credited toward target + Still needed == Total target, every partner",
                       if (length(bad_identity) == 0) "PASS" else "FAIL",
                       sprintf("%d of %d workbooks violate the identity: %s - must hold by construction (both figures are per-stratum capped/floored against the same target), a violation means the headline is being computed some other way again",
                               length(bad_identity), n_checked, paste(bad_identity, collapse = "; ")),
                       length(bad_identity))
  log <- check_result(log, "oversampling_rollup_integrity", "README 'Still needed' equals the sum of the Strata Summary sheet's per-row Still Needed, every partner",
                       if (length(bad_still) == 0) "PASS" else "FAIL",
                       sprintf("%d of %d workbooks disagree: %s - the headline must be the floor-then-sum of the per-stratum rows, never one subtraction at partner grain (the pre-2026-09-21 bug)",
                               length(bad_still), n_checked, paste(bad_still, collapse = "; ")),
                       length(bad_still))
  log <- check_result(log, "oversampling_rollup_integrity", "README 'Credited toward target' equals the sum of per-row min(Achieved, Target) on the Strata Summary sheet, every partner",
                       if (length(bad_credited) == 0) "PASS" else "FAIL",
                       sprintf("%d of %d workbooks disagree: %s", length(bad_credited), n_checked, paste(bad_credited, collapse = "; ")),
                       length(bad_credited))
  log <- check_result(log, "oversampling_rollup_integrity", "Partners whose raw Achieved meets/exceeds target while strata are still short (informational - the exact case the old headline hid)",
                       "PASS",
                       sprintf("%d partner(s): %s", length(masked_now_visible), if (length(masked_now_visible) == 0) "none" else paste(masked_now_visible, collapse = "; ")),
                       length(masked_now_visible))

  # ---- Overlay-blind to-do lists (found by Resampling 2026-09-21, same
  # day, mid-sweep): the 2026-09-19 overlay exclusion (cluster_
  # accessibility_overlay.csv + target_correction_dropped_clusters.csv)
  # landed in build_partner_dc_packages.py only, never its daily-tier
  # sibling refresh_partner_workbooks_daily.py - so any workbook the daily
  # tier writes lists partner-reported-inaccessible and Task-5-dropped
  # clusters as collectable (265 rows nationally when found). This check
  # is tier-agnostic: whichever script last wrote the workbook, no
  # overlay-excluded cluster may appear on "Available to Collect". -------
  overlay_ids <- character(0)
  for (f in c("resampling/output/cluster_accessibility_overlay.csv", "resampling/output/target_correction_dropped_clusters.csv")) {
    p <- file.path(SAMPLING_ROOT, f)
    if (file.exists(p)) {
      d <- tryCatch(read.csv(p, stringsAsFactors = FALSE), error = function(e) NULL)
      if (!is.null(d) && "cluster_id" %in% names(d)) overlay_ids <- c(overlay_ids, trimws(d$cluster_id))
    }
  }
  overlay_ids <- unique(overlay_ids[nzchar(overlay_ids)])
  leaked_total <- 0; leaked_by_partner <- character(0); no_sheet <- character(0)
  for (p in partner_dirs) {
    wb <- list.files(file.path(PKG_ROOT, p), pattern = "sampling_points_summary\\.xlsx$", full.names = TRUE)
    if (length(wb) == 0) next
    atc <- tryCatch(read_excel(wb[1], sheet = "Available to Collect"), error = function(e) NULL)
    if (is.null(atc)) { no_sheet <- c(no_sheet, p); next }
    id_col <- intersect(c("Cluster ID", "cluster_id"), names(atc))
    if (length(id_col) == 0) { no_sheet <- c(no_sheet, p); next }
    n_leak <- length(unique(as.character(atc[[id_col[1]]])[as.character(atc[[id_col[1]]]) %in% overlay_ids]))
    if (n_leak > 0) { leaked_total <- leaked_total + n_leak; leaked_by_partner <- c(leaked_by_partner, sprintf("%s %d", p, n_leak)) }
  }
  log <- check_result(log, "oversampling_rollup_integrity", "No overlay-excluded cluster (accessibility overlay / Task-5 drop) appears on any partner's 'Available to Collect' sheet",
                       if (leaked_total == 0 && length(no_sheet) == 0) "PASS" else "FAIL",
                       sprintf("%d overlay-excluded cluster(s) listed as collectable across partners (%s)%s - both workbook tiers apply the exclusion via scripts/shared/cluster_exclusions.py since 2026-09-21 (08fa533; before that the daily tier had no loaders), so a nonzero count means that partner's workbook hasn't been rebuilt since the overlay or drop list last changed (e.g. packages deferred after an accessibility merge), or the shared rule drifted",
                               leaked_total, if (length(leaked_by_partner) == 0) "none" else paste(leaked_by_partner, collapse = ", "),
                               if (length(no_sheet) == 0) "" else sprintf("; %d workbook(s) with no readable Available to Collect sheet: %s", length(no_sheet), paste(no_sheet, collapse = ", "))),
                       leaked_total)
  log
}
